services:
  - type: web
    name: Abu-MD
    env: node
    branch: main
    repo: https://github.com/Afx-Abu/Abu-MD.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SHABAN-SOBX-MD~yY8HHawQ#AcHRnosPzNOsGQlWu9GlGGEU0IJEQi4lZxp3A8n2S44
        sync: false

